Update run-application.yml

diff --git a/.github/workflows/run-application.yml b/.github/workflows/run-application.yml
--- a/.github/workflows/run-application.yml
+++ b/.github/workflows/run-application.yml
@@ -1,7 +1,12 @@
 name: Release job
 on: 
   workflow_dispatch:
-
+  
+env:
+  RP_INSTANCE: 'https://reportportal.epam.com'
+  SCRIPT_TIMEOUT_SECONDS: 60
+  REQUEST_TIMEOUT_SECONDS: 60
+  
 jobs:
   check-tag:
     runs-on: ubuntu-latest
@@ -75,7 +80,30 @@ jobs:
       - name: Create .env file
         run: cp /home/ubuntu/.env demo-ui-test
       - name: npm test 
-        run: cd demo-ui-test && npm test 
+        run:  | 
+          cd demo-ui-test
+          npm test | tee ./console.log || true
+          sed -rn 's/ReportPortal Launch UUID: ([^\\r\\n]+)/LAUNCH_UUID=\1/ p' ./console.log  >> "$GITHUB_ENV"
+      - name: Quality Gate
+        run: |
+          echo "Quality gate"
+          echo "LAUNCH_UUID: $LAUNCH_UUID"
+          QUALITY_GATE_STATUS=""
+          START_TIME=$(date +%s)
+          while ( [ -z "$QUALITY_GATE_STATUS" ] || [ "$QUALITY_GATE_STATUS" == "UNDEFINED" ] ) && [ $(( $(date +%s) - START_TIME )) -lt ${{ env.SCRIPT_TIMEOUT_SECONDS }} ]; do
+            echo "Waiting for quality gate status..."
+            sleep 10
+            QUALITY_GATE_JSON=$(curl -s -H "Authorization: Bearer ${{ secrets.RP_DEMO_KEY }}" --max-time "${{ env.REQUEST_TIMEOUT_SECONDS }}" "${{ env.RP_INSTANCE }}/api/v1/report_portal_demo/launch/${LAUNCH_UUID}")
+            QUALITY_GATE_STATUS=$(echo "$QUALITY_GATE_JSON" | jq -r '.metadata.qualityGate.status // empty')
+          done
+          if [ "$QUALITY_GATE_STATUS" != "PASSED" ]; then
+            echo "Quality gate status: $QUALITY_GATE_STATUS"
+            echo "Failing the pipeline."
+            exit 1
+          else
+            echo "Quality gate status: $QUALITY_GATE_STATUS"
+            echo "Pipeline passed."
+          fi
         
      # - name: Run Docker compose down
      #   run: docker compose -p reportportal down
